# -*- coding: utf-8 -*-
"""UWB_Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_083Q9eNNlZ6gHQRM-f-uz35Jij8rpIV
"""

# DNN

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import regularizers, optimizers
from google.colab import drive
drive.mount('/content/drive')

import matplotlib.pyplot as plt

# 재현성
np.random.seed(0)
tf.random.set_seed(0)


# =========================================
# 1) 데이터 로드 (헤더 없음 주의)
# =========================================
train_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Toa_sort.csv", header=None)
test_df  = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Toa_test_sort.csv", header=None)

print("Train raw shape:", train_df.shape)
print("Test  raw shape:", test_df.shape)

# 열 의미 가정:
# 0: x, 1: y, 2: anchor_id(1~8), 3: ToA, 4~: CIR(128개)
num_anchor = 8

# =========================================
# 2) 8개씩 묶을 수 있는지 확인 + anchor 패턴 검사
# =========================================
train_arr = train_df.values
test_arr  = test_df.values

N_train_row, n_cols = train_arr.shape
N_test_row,  _      = test_arr.shape

assert N_train_row % num_anchor == 0, "train 행 수가 8의 배수가 아님"
assert N_test_row  % num_anchor == 0, "test 행 수가 8의 배수가 아님"

N_train_sample = N_train_row // num_anchor   # 위치 개수
N_test_sample  = N_test_row  // num_anchor

# (N_pos, 8, n_cols)로 묶기
train_group = train_arr.reshape(N_train_sample, num_anchor, n_cols)
test_group  = test_arr.reshape(N_test_sample,  num_anchor, n_cols)

print("Train grouped:", train_group.shape)  # (N_pos, 8, n_cols)
print("Test  grouped:", test_group.shape)

# anchor id가 각 세트마다 [1,2,3,4,5,6,7,8]인지 검사
train_anchor = train_group[:, :, 2]   # shape: (N_train_sample, 8)
test_anchor  = test_group[:, :, 2]

expected = np.arange(1, num_anchor+1).reshape(1, num_anchor)  # (1,8)

assert np.all(train_anchor == expected), "train에서 anchor 순서가 1~8이 아닌 세트가 있음"
assert np.all(test_anchor  == expected), "test에서 anchor 순서가 1~8이 아닌 세트가 있음"

# =========================================
# 3) 라벨 y: 8행 → 1위치 라벨로 축소
#    (각 위치에서 첫 번째 행의 (x,y)를 사용)
# =========================================
y_train_row = train_arr[:, 0:2]   # (N_train_row, 2)
y_test_row  = test_arr[:, 0:2]

y_train_group = y_train_row.reshape(N_train_sample, num_anchor, 2)
y_test_group  = y_test_row.reshape(N_test_sample,  num_anchor, 2)

y_train = y_train_group[:, 0, :]   # (N_train_sample, 2)
y_test  = y_test_group[:, 0, :]    # (N_test_sample,  2)

print("y_train shape:", y_train.shape)
print("y_test  shape:", y_test.shape)

# =========================================
# 4) 입력 feature: ToA + CIR (행 기준)
# =========================================
ToA_train_row = train_arr[:, 3].reshape(-1, 1)   # (N_train_row, 1)
ToA_test_row  = test_arr[:, 3].reshape(-1, 1)

CIR_train_row = train_arr[:, 4:]                 # (N_train_row, 128)
CIR_test_row  = test_arr[:, 4:]

n_cir = CIR_train_row.shape[1]
print("CIR length:", n_cir)

# =========================================
# 5) 스케일링 (행 기준으로 fit → 이후 8개씩 묶어서 사용)
# =========================================
scaler_cir = StandardScaler()
CIR_train_scaled_row = scaler_cir.fit_transform(np.log1p(CIR_train_row))
CIR_test_scaled_row  = scaler_cir.transform(np.log1p(CIR_test_row))

scaler_toa = StandardScaler()
ToA_train_scaled_row = scaler_toa.fit_transform(ToA_train_row)
ToA_test_scaled_row  = scaler_toa.transform(ToA_test_row)

scaler_y = StandardScaler()
y_train_scaled = scaler_y.fit_transform(y_train)
y_test_scaled  = scaler_y.transform(y_test)

# =========================================
# 6) 8개 비콘을 한 세트로 묶기
#    (N_sample, 8, feature_per_beacon) → (N_sample, 전체 feature)
#    beacon당 feature = 1(ToA) + n_cir(CIR)
# =========================================
# ToA: (N_row,1) → (N_sample, 8, 1)
ToA_train_group = ToA_train_scaled_row.reshape(N_train_sample, num_anchor, 1)
ToA_test_group  = ToA_test_scaled_row.reshape(N_test_sample,  num_anchor, 1)

# CIR: (N_row,n_cir) → (N_sample, 8, n_cir)
CIR_train_group = CIR_train_scaled_row.reshape(N_train_sample, num_anchor, n_cir)
CIR_test_group  = CIR_test_scaled_row.reshape(N_test_sample,  num_anchor, n_cir)

# 비콘 하나당 feature = 1(ToA) + n_cir(CIR)
X_train_group = np.concatenate([ToA_train_group, CIR_train_group], axis=2)  # (N_sample, 8, 1+n_cir)
X_test_group  = np.concatenate([ToA_test_group,  CIR_test_group],  axis=2)

# 전체를 1D 벡터로 펼침
X_train = X_train_group.reshape(N_train_sample, -1)   # (N_sample, 8*(1+n_cir))
X_test  = X_test_group.reshape(N_test_sample,  -1)

print("X_train shape:", X_train.shape)
print("X_test  shape:", X_test.shape)

# =========================================
# 7) 위치 샘플 단위로 먼저 섞기 (train/val 분포 맞추기)
# =========================================
idx = np.arange(N_train_sample)
np.random.shuffle(idx)

X_train = X_train[idx]
y_train = y_train[idx]
y_train_scaled = y_train_scaled[idx]

# =========================================
# 8) DNN 모델 정의 (8비콘 세트 입력용)
# =========================================
model = keras.Sequential([
    layers.Dense(256, input_shape=(X_train.shape[1],),
                 kernel_regularizer=regularizers.l2(1e-4)),
    layers.LeakyReLU(alpha=0.01),
    layers.Dropout(0.3),

    layers.Dense(128, kernel_regularizer=regularizers.l2(1e-4)),
    layers.LeakyReLU(alpha=0.01),
    layers.Dropout(0.3),

    layers.Dense(64, kernel_regularizer=regularizers.l2(1e-4)),
    layers.LeakyReLU(alpha=0.01),
    layers.Dropout(0.3),

    layers.Dense(2)  # (x, y)
])

optimizer = optimizers.Adam(learning_rate=1e-4)
model.compile(optimizer=optimizer, loss='mse', metrics=['mae'])

print("\n--- DNN 모델 구조 (8비콘 세트 입력) ---")
model.summary()

# 콜백: EarlyStopping
early_stop = keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

# =========================================
# 9) 학습 (위치 단위 샘플 기준)
# =========================================
history = model.fit(
    X_train, y_train_scaled,
    epochs=50,
    batch_size=64,
    validation_split=0.1,   # 맨 뒤 10%를 val로 사용 (이미 섞어 놓음)
    shuffle=True,
    callbacks=[early_stop],
    verbose=1
)

# =========================================
# 10) Train 세트 예측 및 오차
# =========================================
y_train_pred_scaled = model.predict(X_train, verbose=0)
y_train_pred = scaler_y.inverse_transform(y_train_pred_scaled)

x_hat_tr = y_train_pred[:, 0]
y_hat_tr = y_train_pred[:, 1]

x_true_tr = y_train[:, 0]
y_true_tr = y_train[:, 1]

train_errors = np.sqrt((x_hat_tr - x_true_tr)**2 + (y_hat_tr - y_true_tr)**2)

print("=== Train set performance (after training) ===")
print("Train mean error [m]   :", np.mean(train_errors))
print("Train median error [m] :", np.median(train_errors))
print("Train RMSE [m]         :", np.sqrt(np.mean(train_errors**2)))

# =========================================
# 11) Test 세트 예측 및 오차
# =========================================
y_pred_scaled = model.predict(X_test, verbose=0)
y_pred = scaler_y.inverse_transform(y_pred_scaled)

x_hat = y_pred[:, 0]
y_hat = y_pred[:, 1]

x_true = y_test[:, 0]
y_true = y_test[:, 1]

errors = np.sqrt((x_hat - x_true)**2 + (y_hat - y_true)**2)

mean_error = np.mean(errors)
median_error = np.median(errors)
rmse = np.sqrt(np.mean(errors**2))

print("=== Test set performance ===")
#print("Mean error [m]   :", mean_error)
#print("Median error [m] :", median_error)
#print("RMSE [m]         :", rmse)

print(f"TP RMSE:   {rmse:.3f} m")
print(f"TP Median: {median_error:.3f} m")
print(f"TP Mean:   {mean_error:.3f} m")

# Test 세트 error 저장 (CDF 비교용)

Error_tp_dnn = errors
np.save("error_tp_dnn.npy", Error_tp_dnn)
print("Saved: error_tp_dnn.npy")
model.save("dnn_final.h5")

# =========================================
# 12) Test 전체 산포도
# =========================================
plt.figure()
plt.plot(x_true, y_true, 'rx', label='Ground Truth')
plt.plot(x_hat, y_hat, 'bo', label='Predicted')
plt.xlabel('x [m]')
plt.ylabel('y [m]')
plt.title('Predicted vs ground truth positions (Test, all)')
plt.axis('equal')
plt.legend()
plt.grid(True)
plt.show()

# =========================================
# 13) Test – 오차가 작은 샘플만 시각화 (percent 기반)
#      GT는 전체, Pred는 상위 p%만
# =========================================
percent = 0.3   # 오차 작은 상위 30%

th = np.quantile(errors, percent)
good_idx = np.where(errors <= th)[0]

print(f"전체 TP 수: {len(errors)}")
print(f"선택된 TP 수 (Top {percent*100:.1f}%): {len(good_idx)}")

# 전체 GT
xt_all = x_true
yt_all = y_true

# 선택된 Pred
xp = x_hat[good_idx]
yp = y_hat[good_idx]

plt.figure(figsize=(6,6))
plt.scatter(xt_all, yt_all, s=5, label='Ground Truth (ALL)', alpha=0.3, c='red')
plt.scatter(xp, yp,       s=5, label=f'Predicted (Top {percent*100:.1f}%)', alpha=0.8, c='blue')
plt.xlabel('x [m]'); plt.ylabel('y [m]')
plt.title('TP Prediction vs Ground Truth (partial Pred)')
plt.axis('equal'); plt.grid(True); plt.legend()
plt.show()

# =========================================
# 14) 손실 곡선 (Train vs Validation)
# =========================================
plt.figure()
plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='val loss')
plt.xlabel('Epoch')
plt.ylabel('MSE loss')
plt.title('Training and validation loss')
plt.legend()
plt.grid(True)
plt.show()

# =========================================
# 15) 위치별 오차 히트맵 (Test)
# =========================================
df_err = pd.DataFrame({
    'x_true': x_true,
    'y_true': y_true,
    'error': errors
})

heat = (
    df_err
    .groupby([
        df_err.x_true.round(1).rename('x'),
        df_err.y_true.round(1).rename('y')
    ])['error']
    .mean()
    .reset_index()
)

vmin = 0
vmax = 5

plt.figure(figsize=(7,6))
sc = plt.scatter(
    heat['x'], heat['y'],
    c=heat['error'],
    s=40,
    cmap='jet',
    vmin=vmin,
    vmax=vmax
)
plt.colorbar(sc, label=f'Mean error [m] (clipped {vmin}~{vmax})')
plt.xlabel('x [m]'); plt.ylabel('y [m]')
plt.title('Localization error heatmap (scaled)')
plt.axis('equal'); plt.grid(True)
plt.show()

# CNN 1D

# ============================================================
# 0. 기본 설정
# ============================================================
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, regularizers
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

from google.colab import drive
drive.mount('/content/drive')

tf.random.set_seed(42)
np.random.seed(42)


# ============================================================
# 1. 데이터 로드
# ============================================================
train_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Toa_sort.csv", header=None)
test_df  = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Toa_test_sort.csv", header=None)

train_arr = train_df.values
test_arr  = test_df.values

num_anchor = 8
n_cols = train_arr.shape[1]
n_cir = n_cols - 4   # CIR length 128

N_train_row = len(train_arr)
N_test_row  = len(test_arr)

assert N_train_row % num_anchor == 0
assert N_test_row  % num_anchor == 0

N_train = N_train_row // num_anchor
N_test  = N_test_row  // num_anchor

train_group = train_arr.reshape(N_train, num_anchor, n_cols)
test_group  = test_arr.reshape(N_test, num_anchor, n_cols)


# ============================================================
# 2. 라벨
# ============================================================
y_train_raw = train_group[:, 0, 0:2]
y_test_raw  = test_group[:, 0, 0:2]


# ============================================================
# 3. ToA / CIR / Energy
# ============================================================
ToA_train_row = train_arr[:, 3].reshape(-1,1)
ToA_test_row  = test_arr[:, 3].reshape(-1,1)

CIR_train_row = train_arr[:, 4:]
CIR_test_row  = test_arr[:, 4:]

CIR_E_train = np.sum(CIR_train_row**2, axis=1, keepdims=True)
CIR_E_test  = np.sum(CIR_test_row**2, axis=1, keepdims=True)


# ============================================================
# 4. Scaling
# ============================================================
scaler_cir = StandardScaler()
CIR_train_scaled_row = scaler_cir.fit_transform(np.log1p(CIR_train_row))
CIR_test_scaled_row  = scaler_cir.transform(np.log1p(CIR_test_row))

scaler_toa = StandardScaler()
ToA_train_scaled = scaler_toa.fit_transform(ToA_train_row)
ToA_test_scaled  = scaler_toa.transform(ToA_test_row)

scaler_E = StandardScaler()
CIR_E_train_scaled = scaler_E.fit_transform(np.log1p(CIR_E_train))
CIR_E_test_scaled  = scaler_E.transform(np.log1p(CIR_E_test))

scaler_y = StandardScaler()
y_train = scaler_y.fit_transform(y_train_raw)
y_test  = scaler_y.transform(y_test_raw)


# ============================================================
# 5. 8 비콘 묶기 → (8,130) → Flatten → (1040,1)
# ============================================================
ToA_train_group = ToA_train_scaled.reshape(N_train, num_anchor, 1)
ToA_test_group  = ToA_test_scaled.reshape(N_test, num_anchor, 1)

CIR_train_group = CIR_train_scaled_row.reshape(N_train, num_anchor, n_cir)
CIR_test_group  = CIR_test_scaled_row.reshape(N_test, num_anchor, n_cir)

CIR_E_train_group = CIR_E_train_scaled.reshape(N_train, num_anchor, 1)
CIR_E_test_group  = CIR_E_test_scaled.reshape(N_test, num_anchor, 1)

# shape = (N, 8, 130)
X_train_group = np.concatenate([ToA_train_group, CIR_train_group, CIR_E_train_group], axis=2)
X_test_group  = np.concatenate([ToA_test_group, CIR_test_group, CIR_E_test_group], axis=2)

# Flatten → (N, 8*130 = 1040, 1)
X_train_cnn = X_train_group.reshape(N_train, -1, 1).astype("float32")
X_test_cnn  = X_test_group.reshape(N_test,  -1, 1).astype("float32")

print("1D CNN Input Shape:", X_train_cnn.shape)


# ============================================================
# 6. Train/Val Split
# ============================================================
X_tr, X_val, y_tr, y_val = train_test_split(
    X_train_cnn, y_train, test_size=0.2, shuffle=True, random_state=42
)


# ============================================================
# 7. 1D CNN 모델 구성
# ============================================================
inputs = keras.Input(shape=(X_train_cnn.shape[1], 1))

x = layers.Conv1D(64, 5, padding="same", activation="relu")(inputs)
x = layers.Conv1D(64, 5, padding="same", activation="relu")(x)
x = layers.MaxPooling1D(2)(x)

x = layers.Conv1D(128, 5, padding="same", activation="relu")(x)
x = layers.Conv1D(128, 5, padding="same", activation="relu")(x)
x = layers.MaxPooling1D(2)(x)

x = layers.Flatten()(x)
x = layers.Dense(256, activation="relu")(x)
x = layers.Dropout(0.2)(x)

x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.15)(x)

outputs = layers.Dense(2)(x)

model = keras.Model(inputs, outputs)
model.compile(optimizer=keras.optimizers.Adam(3e-4), loss="mse")

model.summary()


# ============================================================
# 8. 콜백
# ============================================================
es = EarlyStopping(monitor="val_loss", patience=12, restore_best_weights=True, verbose=1)
lr = ReduceLROnPlateau(monitor="val_loss", patience=6, factor=0.5, min_lr=1e-5, verbose=1)


# ============================================================
# 9. 학습
# ============================================================
history = model.fit(
    X_tr, y_tr, epochs=120, batch_size=64,
    validation_data=(X_val, y_val),
    callbacks=[es, lr], verbose=1
)


# ============================================================
# 10. 평가 + 저장
# ============================================================
def compute_errors(pred, real):
    return np.linalg.norm(pred - real, axis=1)

pred_tp = scaler_y.inverse_transform(model.predict(X_test_cnn))
err_tp = compute_errors(pred_tp, y_test_raw)

np.save("error_tp_1dcnn.npy", err_tp)
np.save("y_test_raw.npy", y_test_raw)
model.save("cnn_1d_final.h5")


# ============================================================
# 11. 성능 지표 출력
# ============================================================
print("\n===== 1D CNN TP 성능 =====")
print(f"RMSE   : {np.sqrt(np.mean(err_tp**2)):.3f} m")
print(f"Median : {np.median(err_tp):.3f} m")
print(f"Mean   : {np.mean(err):.3f} m")
print(f"P90    : {np.percentile(err_tp,90):.3f} m")
print(f"P95    : {np.percentile(err_tp,95):.3f} m")

for th in [0.5,1,2]:
    print(f"<= {th}m : {np.mean(err_tp<=th)*100:.1f}%")

# ============================================================
# 12. Training / Validation Loss Curve
# ============================================================

plt.figure(figsize=(8,6))
plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='val loss')
plt.xlabel("Epoch")
plt.ylabel("MSE loss")
plt.title("Training and validation loss")
plt.grid(True)
plt.legend()
plt.show()



# ============================================================
# 13. Heatmap
# ============================================================
df = pd.DataFrame({
    "x": y_test_raw[:,0],
    "y": y_test_raw[:,1],
    "err": err_tp
})

heat = df.groupby([df.x.round(1), df.y.round(1)])["err"].mean().reset_index()

plt.figure(figsize=(7,6))
sc = plt.scatter(
    heat["x"], heat["y"],
    c=heat["err"], s=40,
    cmap="jet", vmin=0, vmax=5
)
plt.colorbar(sc, label="Mean Error [m]")
plt.title("1D CNN Error Heatmap")
plt.axis("equal"); plt.grid(True)
plt.show()

# CNN 2D

# ============================================================
# 0. 기본 설정
# ============================================================
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, regularizers
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from google.colab import drive
drive.mount('/content/drive')

tf.random.set_seed(42)
np.random.seed(42)


# ============================================================
# 1. 데이터 로드
# ============================================================
train_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Toa_sort.csv", header=None)
test_df  = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Toa_test_sort.csv", header=None)

train_arr = train_df.values
test_arr  = test_df.values

num_anchor = 8
n_cols = train_arr.shape[1]
n_cir = n_cols - 4   # CIR length 128

N_train_row = len(train_arr)
N_test_row  = len(test_arr)

assert N_train_row % num_anchor == 0
assert N_test_row  % num_anchor == 0

N_train = N_train_row // num_anchor
N_test  = N_test_row  // num_anchor

train_group = train_arr.reshape(N_train, num_anchor, n_cols)
test_group  = test_arr.reshape(N_test, num_anchor, n_cols)


# ============================================================
# 2. 라벨 (x,y)
# ============================================================
y_train_raw = train_group[:, 0, 0:2]
y_test_raw  = test_group[:,  0, 0:2]


# ============================================================
# 3. ToA / CIR / CIR Energy
# ============================================================
ToA_train_row = train_arr[:, 3].reshape(-1,1)
ToA_test_row  = test_arr[:, 3].reshape(-1,1)

CIR_train_row = train_arr[:, 4:]
CIR_test_row  = test_arr[:, 4:]

# CIR Energy = sum(CIR^2)
CIR_E_train = np.sum(CIR_train_row**2, axis=1, keepdims=True)
CIR_E_test  = np.sum(CIR_test_row**2, axis=1, keepdims=True)


# ============================================================
# 4. Scaling
# ============================================================
scaler_cir = StandardScaler()
CIR_train_scaled_row = scaler_cir.fit_transform(np.log1p(CIR_train_row))
CIR_test_scaled_row  = scaler_cir.transform(np.log1p(CIR_test_row))

scaler_toa = StandardScaler()
ToA_train_scaled = scaler_toa.fit_transform(ToA_train_row)
ToA_test_scaled  = scaler_toa.transform(ToA_test_row)

scaler_E = StandardScaler()
CIR_E_train_scaled = scaler_E.fit_transform(np.log1p(CIR_E_train))
CIR_E_test_scaled  = scaler_E.transform(np.log1p(CIR_E_test))

scaler_y = StandardScaler()
y_train = scaler_y.fit_transform(y_train_raw)
y_test  = scaler_y.transform(y_test_raw)


# ============================================================
# 5. 8 비콘 묶기 → (8, 130): ToA + CIR128 + Energy
# ============================================================
ToA_train_group = ToA_train_scaled.reshape(N_train, num_anchor, 1)
ToA_test_group  = ToA_test_scaled.reshape(N_test, num_anchor, 1)

CIR_train_group = CIR_train_scaled_row.reshape(N_train, num_anchor, n_cir)
CIR_test_group  = CIR_test_scaled_row.reshape(N_test, num_anchor, n_cir)

CIR_E_train_group = CIR_E_train_scaled.reshape(N_train, num_anchor, 1)
CIR_E_test_group  = CIR_E_test_scaled.reshape(N_test, num_anchor, 1)

# shape → (N, 8, 130)
X_train_group = np.concatenate([ToA_train_group, CIR_train_group, CIR_E_train_group], axis=2)
X_test_group  = np.concatenate([ToA_test_group, CIR_test_group, CIR_E_test_group], axis=2)

X_train_cnn = X_train_group[..., np.newaxis].astype("float32")
X_test_cnn  = X_test_group[..., np.newaxis].astype("float32")


# ============================================================
# 6. Train/Val split
# ============================================================
X_tr, X_val, y_tr, y_val = train_test_split(
    X_train_cnn, y_train, test_size=0.2, shuffle=True, random_state=42
)


# ============================================================
# 7. Attention Blocks
# ============================================================
def channel_attention(inputs, ratio=8):
    ch = int(inputs.shape[-1])
    gap = layers.GlobalAveragePooling2D()(inputs)
    fc1 = layers.Dense(ch // ratio, activation="relu")(gap)
    fc2 = layers.Dense(ch, activation="sigmoid")(fc1)
    scale = layers.Reshape((1,1,ch))(fc2)
    return layers.Multiply()([inputs, scale])

def ap_attention_softmax(inputs):
    # (B, 8, W, C) → (B, 8, C)
    squeeze = layers.Lambda(lambda x: tf.reduce_mean(x, axis=2))(inputs)
    score = layers.Dense(1)(squeeze)
    score = layers.Softmax(axis=1)(score)
    score = layers.Reshape((8,1,1))(score)
    return layers.Multiply()([inputs, score])



# ============================================================
# 8. 2D CNN 모델 구성
# ============================================================
inputs = keras.Input(shape=(8,130,1))

# --- Block 1 ---
x1 = layers.Conv2D(32,(3,5),padding="same",activation="swish")(inputs)
x2 = layers.Conv2D(16,(5,9),padding="same",activation="swish")(inputs)
x = layers.Concatenate()([x1,x2])
x = layers.BatchNormalization()(x)

# --- Block 2 (MS)
x1 = layers.Conv2D(64,(3,5),padding="same",activation="swish")(x)
x2 = layers.Conv2D(32,(5,9),padding="same",activation="swish")(x)
x = layers.Concatenate()([x1,x2])
x = layers.BatchNormalization()(x)
x = layers.MaxPooling2D((1,2))(x)

# --- Block 3 (Dilated + Attention)
x = layers.Conv2D(128,(3,3),activation="swish",padding="same")(x)
x = layers.Conv2D(128,(3,3),activation="swish",padding="same",dilation_rate=2)(x)
x = layers.BatchNormalization()(x)

x = channel_attention(x)
x = ap_attention_softmax(x)
x = layers.GlobalAveragePooling2D()(x)

# --- Dense Head + Residual 2 Blocks ---
x = layers.Dense(128,activation="swish")(x)
x = layers.Dropout(0.2)(x)

for _ in range(2):
    res = x
    h = layers.Dense(128,activation="swish")(x)
    h = layers.Dense(128)(h)
    x = layers.Add()([res,h])
    x = layers.Activation("swish")(x)

x = layers.Dense(64,activation="swish")(x)
x = layers.Dropout(0.15)(x)

outputs = layers.Dense(2)(x)

model = keras.Model(inputs, outputs)
model.compile(optimizer=keras.optimizers.Adam(3e-4), loss="mse")


# ============================================================
# 9. 콜백
# ============================================================
es = EarlyStopping(monitor="val_loss", patience=15, min_delta=1e-4,
                   restore_best_weights=True, verbose=1)
lr = ReduceLROnPlateau(monitor="val_loss", factor=0.5,
                       patience=6, min_lr=1e-5, verbose=1)


# ============================================================
# 10. 학습
# ============================================================
history = model.fit(
    X_tr, y_tr, epochs=120, batch_size=64,
    validation_data=(X_val,y_val),
    callbacks=[es,lr], verbose=1
)


# ============================================================
# 11. 평가 + 저장
# ============================================================
def compute_errors(pred, real):
    diff = pred - real
    dist = np.linalg.norm(diff, axis=1)
    return dist

# RP
pred_rp   = scaler_y.inverse_transform(model.predict(X_train_cnn))
err_rp    = compute_errors(pred_rp, y_train_raw)

# TP
pred_tp   = scaler_y.inverse_transform(model.predict(X_test_cnn))
err_tp    = compute_errors(pred_tp, y_test_raw)

np.save("error_tp_2dcnn.npy", err_tp)
np.save("y_test_raw.npy", y_test_raw)
model.save("cnn_2d_final.h5")

# ============================================================
# 12. 성능 지표 추가 출력
# ============================================================
def summarize(name, err):
    print(f"\n[{name}]")
    print(f"RMSE   : {np.sqrt(np.mean(err**2)):.3f} m")
    print(f"Median : {np.median(err):.3f} m")
    print(f"Mean   : {np.mean(err):.3f} m")
    print(f"P90    : {np.percentile(err,90):.3f} m")
    print(f"P95    : {np.percentile(err,95):.3f} m")
    for th in [0.5,1,2]:
        print(f"<= {th}m : {np.mean(err<=th)*100:.1f}%")

summarize("2D CNN (TP)", err_tp)

# ============================================================
# 13. Loss Curve
# ============================================================
plt.figure(figsize=(7,5))
plt.plot(history.history["loss"], label="train loss")
plt.plot(history.history["val_loss"], label="val loss")
plt.xlabel("Epoch")
plt.ylabel("MSE loss")
plt.title("Training and validation loss")
plt.grid(True)
plt.legend()
plt.show()

# ============================================================
# 14. Error Heatmap
# ============================================================
df = pd.DataFrame({
    "x": y_test_raw[:,0],
    "y": y_test_raw[:,1],
    "err": err_tp
})

heat = df.groupby([df.x.round(1), df.y.round(1)])["err"].mean().reset_index()

plt.figure(figsize=(7,6))
sc = plt.scatter(
    heat["x"], heat["y"], c=heat["err"], s=40,
    cmap="jet", vmin=0, vmax=5
)
plt.colorbar(sc, label="Mean error [m]")
plt.title("2D CNN Error Heatmap")
plt.axis("equal"); plt.grid(True)
plt.show()

# ===============================================
# 📌 UWB Positioning — Full Model Comparison Script
#    (DNN vs 1D CNN vs 2D CNN)
# ===============================================
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# -----------------------------
# 1) Load saved results
# -----------------------------
y_test    = np.load("y_test_raw.npy")        # (N,2)
err_dnn   = np.load("error_tp_dnn.npy")
err_cnn1d = np.load("error_tp_1dcnn.npy")
err_cnn2d = np.load("error_tp_2dcnn.npy")

model_errors = {
    "DNN": err_dnn,
    "1D CNN": err_cnn1d,
    "2D CNN": err_cnn2d
}

# -----------------------------
# 2) 성능 지표 계산 함수
# -----------------------------
def summarize_metrics(name, err):
    rmse = np.sqrt(np.mean(err**2))
    median = np.median(err)
    p90 = np.percentile(err, 90)
    p95 = np.percentile(err, 95)

    print(f"\n===== {name} =====")
    print(f"RMSE   : {rmse:.3f} m")
    print(f"Median : {median:.3f} m")
    print(f"P90    : {p90:.3f} m")
    print(f"P95    : {p95:.3f} m")

    for th in [0.5, 1.0, 2.0]:
        rate = np.mean(err <= th) * 100
        print(f"<= {th}m : {rate:.1f}%")

    return rmse, median, p90, p95

# -----------------------------
# 3) 지표 출력
# -----------------------------
print("=========================================")
print("📌 Performance Summary (TP Set)")
print("=========================================")

metrics = {}
for name, err in model_errors.items():
    metrics[name] = summarize_metrics(name, err)


# ===============================================
# 4) CDF Plot (세 모델 + P90 표시)
# ===============================================
def compute_cdf(err):
    err_sorted = np.sort(err)
    cdf = np.arange(1, len(err_sorted) + 1) / len(err_sorted)
    return err_sorted, cdf

plt.figure(figsize=(8,6))

for name, err in model_errors.items():
    x, cdf = compute_cdf(err)
    plt.plot(x, cdf, label=name)

# P90 수직선 표시
for name, err in model_errors.items():
    p90 = np.percentile(err, 90)
    plt.axvline(p90, linestyle="--", alpha=0.4)

plt.xlabel("Positioning error [m]")
plt.ylabel("CDF")
plt.title("CDF Comparison (DNN vs 1D vs 2D CNN)")
plt.grid(True)
plt.legend()
plt.xlim(0, 6)
plt.ylim(0, 1)
plt.show()


# ===============================================
# 5) Gain Heatmap (2D CNN이 얼마나 더 나은가)
# ===============================================

# --------- 2D CNN vs DNN ----------
diff_dnn = err_dnn - err_cnn2d   # 양수 → 2D CNN이 더 좋음

plt.figure(figsize=(7,6))
sc = plt.scatter(
    y_test[:,0], y_test[:,1],
    c=diff_dnn, cmap="bwr",
    s=35, vmin=-2, vmax=2
)
plt.colorbar(sc, label="DNN error - 2D CNN error [m]")
plt.title("Gain Map: 2D CNN Advantage over DNN")
plt.xlabel("x [m]"); plt.ylabel("y [m]")
plt.grid(True); plt.axis("equal")
plt.show()


# --------- 2D CNN vs 1D CNN ----------
diff_1d = err_cnn1d - err_cnn2d   # 양수 → 2D CNN이 더 좋음

plt.figure(figsize=(7,6))
sc = plt.scatter(
    y_test[:,0], y_test[:,1],
    c=diff_1d, cmap="bwr",
    s=35, vmin=-2, vmax=2
)
plt.colorbar(sc, label="1D CNN error - 2D CNN error [m]")
plt.title("Gain Map: 2D CNN Advantage over 1D CNN")
plt.xlabel("x [m]"); plt.ylabel("y [m]")
plt.grid(True); plt.axis("equal")
plt.show()


print("\n📌 All evaluation complete!")